import type { Metadata } from "next";
import "./globals.css";
import { MainMenu } from "./components/MainMenu";
import { LayoutProvider } from "./contexts/LayoutContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutProvider>
          <MainMenu />
          <div className="container mx-auto max-w-6xl px-4 md:px-6">
            {children}
          </div>
        </LayoutProvider>
      </body>
    </html>
  );
}
